# Esercitazione 4

## Istruzioni
Valgono le stesse istruzioni delle esercitazioni precedenti. 

Scrivi il programma Python nella cella sotto il testo dell'esercizio (o creane una nuova). Stampa sempre a video il risultato finale per verificare la correttezza dell'esercizio.  Talvolta richiamiamo alcuni concetti importanti in una cella di codice sotto il testo dell'esercizio, prova a eseguirla ed eventualmente modificarla per assicurarti di aver capito il necessario.

**Nota.** Alcuni esercizi potrebbero richiedere una semplice risposta a delle domande. In questo caso potete scrivere la soluzione in una cella di tipo "Markdown".  


## Consegna
Valgono le regole delle esercitazioni precedenti.

E' obbligatorio **consegnare la soluzione di tutti gli esercizi** (tranne quelli marcati come opzionali) **entro l'inizio della lezione successiva** (in questo caso entro Lunedi' prossimo), nell'apposito assignment su iCorsi.  Per consegnare:
- eseguire l'intero notebook partendo da zero (`Kernel -> Restart & Run All`), e controllare che le soluzioni siano quelle attese;
- esportare il notebook in formato html (`File -> Download as...`) e consegnare il file risultante.

Nel caso non abbiate potuto completare uno o piu' esercizi, descrivete il problema incontrato e **consegnate comunque il file con il resto delle soluzioni**.

## Esercizio 1 (variabili categoriche)

Scaricare il dataset [profili.csv](https://github.com/rudeboybert/JSE_OkCupid/blob/master/profiles.csv.zip) e importarlo eseguendo i comandi nella cella sotto (assicuratevi di aver salvato il file profili.csv nella stessa cartella del file .ipynb su cui state lavorando, oppure specificate il percorso in cui si trova il file profili.csv). Provate a capire come è fatto il dataset (es., da quanti elementi è composto, quali sono gli attributi, quali valori possono assumere le variabili, etc.). Informazioni sul dataset si possono trovare [QUI](https://nbviewer.jupyter.org/github/alessandro-giusti/profiles_analysis/blob/master/profiles.ipynb)

In [1]:
# Carichiamo il dataset e visualizziamo qualcosa
import pandas as pd
import numpy as np

df = pd.read_csv("profiles.csv")

print(df.columns,"\n\n -------------------------------------")  # Visualizzo le variabili (nomi delle colonne) del dataframe
print(df.head(2),"\n\n -------------------------------------")    # Visualizzo primi 2 elementi del dataframe

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'essay0',
       'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7',
       'essay8', 'essay9', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'orientation', 'pets',
       'religion', 'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object') 

 -------------------------------------
   age       body_type               diet    drinks      drugs  \
0   22  a little extra  strictly anything  socially      never   
1   35         average       mostly other     often  sometimes   

                       education  \
0  working on college/university   
1          working on space camp   

                                              essay0  \
0  about me:<br />\n<br />\ni would love to think...   
1  i am a chef: this is what that means.<br />\n1...   

                                              essay1  \
0  currently working as an international agent f

### 1.1 
Si consideri la variabile "smokes". Quali possibili valori assume questa variabile? Hint: trasforma un array in un set per eliminare i duplicati

In [2]:
# Hints

# Per trasformare una colonna da un dataframe in un numpy array
print(f"Valori della variabile 'diet' per ogni osservazione:\n {df['diet'].values} \n")

# Per visualizzare i diversi valori assunti da un array
print(f"Diversi valori assunti dalla variabile 'diet': {set(df['diet'].values)}")

Valori della variabile 'diet' per ogni osservazione:
 ['strictly anything' 'mostly other' 'anything' ... 'mostly anything'
 'mostly anything' nan] 

Diversi valori assunti dalla variabile 'diet': {nan, 'mostly vegan', 'strictly vegan', 'strictly other', 'strictly halal', 'strictly kosher', 'mostly kosher', 'halal', 'mostly vegetarian', 'strictly anything', 'mostly halal', 'other', 'vegan', 'vegetarian', 'kosher', 'anything', 'strictly vegetarian', 'mostly anything', 'mostly other'}


In [3]:
# Solution

#prendo i fumatori
fumatori =df['smokes'].values
#array di fumatori
#print(fumatori)
#mi faccio dare il set dall'array
fumatoriset=set(fumatori)
print("i valori delLa colonna smokes sono :")
print(fumatoriset)


i valori delLa colonna smokes sono :
{nan, 'yes', 'trying to quit', 'sometimes', 'no', 'when drinking'}


Notate che la variabile "smokes" assume spesso il valore nan (il campo non è stato compilato dall'utente). Eseguiamo la cella sotto (provate a capire come funziona) per creare un nuovo dataset dove eliminiamo le righe (nel nostro caso gli utenti) del dataframe dove il campo "smokes" non è stato compilato. Nel seguito lavoreremo sul nuovo dataset. 

In [4]:
dfNew = df.dropna(subset=['smokes'])
dfNew[['sex', 'smokes']].values # Visualizzo array con sesso dell'utente e la variabile "smokes"

array([['m', 'sometimes'],
       ['m', 'no'],
       ['m', 'no'],
       ...,
       ['m', 'no'],
       ['m', 'trying to quit'],
       ['m', 'sometimes']], dtype=object)

### 1.2 

Raggruppate la variabile "smokes" nei seguenti 2 gruppi: 
- Primo gruppo di nome NoSmoker (questo gruppo identifica i non fumatori: tutti quelli che hanno idicato {no} nel campo "smokes") 
- Secondo gruppo di nome Smoker (questo gruppo identifica per noi tutti i fumatori: quelli che NON hanno indicato 'no' nel campo 'smokes')

Si costruisca la tabella di contingenza per la coppia di variabili "sex" e "smokes" (usando i gruppi definiti sopra).  

Hint1: Non dovete usare particolari comandi Python per calcolare la tabella di contingenza. Ricordatevi come è definita e provate a costruirla voi.  
Hint2: Nella cella sotto trovate un modo veloce per visualizzare una tabella utilizzando il pacchetto Plotly. Maggiori dettagli [QUI](https://plot.ly/python/table/). Oppure visualizzate un dataframe in pandas come visto a lezione. 

In [5]:
# Hint (plot Table)
import plotly.offline as py
import plotly.graph_objs as go
py.init_notebook_mode(connected=True)

# Plotto Tabella con plotly
valori = [ ["Benz", "Diesel"], [9, 0], [109, 9], [65, 11]] # Ogni elemento della lista è una colonna della tabella

trace = go.Table(
                header = dict(values = ["Trazione \t \n Alimentazione", "4x4", "fwd", "bwd"]),
                cells = dict(values = valori) )
py.iplot([trace])

# Plotto Tabella come dataframe
valori = [[9, 109, 65], [0, 9, 11]]
t = pd.DataFrame(valori, index = ["Benz", "Diesel"], columns = ["4x4", "fwd", "bwd"])
t

4x4  fwd  bwd
Benz      9  109   65
Diesel    0    9   11

In [6]:
# Hint2: Potrebbe servirvi per verificare, senza usare un ciclo for, se gli elementi di un array assumono valori contenuti in una lista 
import numpy as np

mioArray = np.array([1,2,3,4,5,6,7])
lista = [2,5,9]
print(np.isin(mioArray,lista))

[False  True False False  True False False]


In [7]:
# Solutiov
#print(tabellaf)
fuma = dfNew["smokes"].values
fumatori = np.full(fuma.shape, "", dtype="object")
for i in range(len(fumatori)):
    if fuma[i] == "no":
        fumatori[i] = "no"
    else:
        fumatori[i] = "fuma"
print(fumatori)

numeronf=np.sum(fumatori=="no")
numerof=len(fuma)-numeronf
#fino a qui è giusto 
sexx = dfNew["sex"].values
numerofemmine=np.sum(sexx=="f")
numeromaschi=len(sexx)-numerofemmine
print(f"le donne sono {numerofemmine}")
print(f"i maschi sono {numeromaschi}")
print()

valori = [[numeronf], [numerof]]
tab = pd.DataFrame(valori, index = ["non fumatori", "fumatori"], columns = ["Numero"])
print(tab)

sex=["m","f"]
smoke=["fuma","no"]
t = np.full((len(sex),len(smoke)), np.nan, dtype=int)
for r in range(len(sex)):
    for s in range(len(smoke)):
        t[r,s] = np.sum((sexx==sex[r]) & (fumatori==smoke[s]))
        print(f"{sex[r]:8} {smoke[s]:12}: {t[r,s]}")
print(t)

print(f"La popolazione totale:{len(sexx)}")
t_rel=np.full(t.shape, np.nan)
for k in range(t.shape[0]): # per ogni riga (indice r)
    for z in range(t.shape[1]): # per ogni colonna (indice s)
        t_rel[k,z] = t[k,z] / len(sexx)
t_rel
#con le frequenze relative marginali abbiamo una percentuale dell'intera popolazione, per esempio i maschi fumatori sono il 12% mentre le femmine non fumatrici sono il 33% ecc
#con le frequenze relative marginali abbiamo una percentuale dell'intera popolazione, per esempio i maschi fumatori sono il 12% mentre le femmine non fumatrici sono il 33% ecc
stampa=pd.DataFrame(t, # dati
             index=sex, # intestazioni di riga
             columns=smoke) # intestazioni di colonna
print(stampa)


['fuma' 'no' 'no' ... 'no' 'fuma' 'fuma']
le donne sono 22065
i maschi sono 32369

              Numero
non fumatori   43896
fumatori       10538
m        fuma        : 6734
m        no          : 25635
f        fuma        : 3804
f        no          : 18261
[[ 6734 25635]
 [ 3804 18261]]
La popolazione totale:54434
   fuma     no
m  6734  25635
f  3804  18261


### 1.3

Rappresentate graficamente i risultati della tabell di contingenza tramite un bar plot

In [8]:
# Solution
print(sex)
trace1 = go.Bar(
    x=sex,
    y=t[:,0],
    name=smoke[0]
)
trace2 = go.Bar(
    x=sex,
    y=t[:,1],
    name=smoke[1]
)

data = [trace1, trace2]
layout = go.Layout(
    barmode='group',
    xaxis=dict(title="sesso"),
    yaxis=dict(title="numero di fumatori")
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='grouped-bar')


['m', 'f']


### 1.4 

Calcolare le frequenze assolute marginali per riga e per colonna. Che informazione ricaviamo dalle frequenze assolute marginali? 

In [9]:
# Solution

c= np.sum(t, axis=1) 
r  = np.sum(t, axis=0)
colonne=r
righe=c
print(f"Frequenze assolute marginali per riga: {c}")#numero di donne vs numero di uomini
print(f"Frequenze assolute marginali per colonna: {r}")#numero fumatori vs numero non fumatori



Frequenze assolute marginali per riga: [32369 22065]
Frequenze assolute marginali per colonna: [10538 43896]


### 1.5 

Calcolare le frequenze relative marginali per riga e per colonna. Che informazione ricaviamo dalle frequenze relative marginali? 

In [10]:
# Solution


print(f"La popolazione totale:{len(sexx)}")
#print(stampa)
t_rel=np.full(t.shape, np.nan)
for k in range(t.shape[0]): # per ogni riga (indice r)
    for z in range(t.shape[1]): # per ogni colonna (indice s)
        t_rel[k,z] = t[k,z] / len(sexx)
t_rel
#con le frequenze relative marginali abbiamo una percentuale dell'intera popolazione, per esempio i maschi fumatori sono il 12% mentre le femmine non fumatrici sono il 33% ecc




La popolazione totale:54434


array([[0.12370945, 0.47093728],
       [0.06988279, 0.33547048]])

### 1.6

Calcolare le frequenze relative condizionate per riga. Che informazioni ricaviamo da queste frequenze?

In [11]:
# Solution
t_cond_rows = np.full(t.shape, np.nan)
for r in range(t.shape[0]): # per ogni riga (indice r)
    for s in range(t.shape[1]): # per ogni colonna (indice s)
        t_cond_rows[r,s] = t[r,s] / c[r]
t_cond_rows

#da queste frequenze relative marginali riusciamo a capire qual'è la percentuale di donne che fuma e quella che non fuma
#e qual'è la percentuali di uomini che fuma e quale no






array([[0.20803856, 0.79196144],
       [0.17239973, 0.82760027]])

### 1.7

Calcolare le frequenze relative condizionate per colonna. Che informazioni ricaviamo da queste frequenze?

In [12]:
# Solution
print(f"colonne :{colonne}")

t_col = np.full(t.shape, np.nan)
for p in range(t.shape[0]): # per ogni riga (indice r)
    for s in range(t.shape[1]): # per ogni colonna (indice s)
        t_col[p,s] = t[p,s] / colonne[s]
t_col

#facendo le frequenze relative condizionate per le colonne invece, troviamo la percentuale di maschi e femmine che fumano sull'intero campione di fumatori
 #nei fumatori il 64% sono maschi e il 36% sono femmine mentre nei non fumatori il 58% maschi e il 42% femmine
# ovviamente nel campione analizzato i maschi sono di più


colonne :[10538 43896]


array([[0.63902069, 0.58399399],
       [0.36097931, 0.41600601]])

### 1.8 (opzionale)
Rispondete alle seguenti domande. 

In [13]:
print(f"Tra i maschi, quale percentuale si dichiara non fumatore? \n")
print(f"Tra i maschi, quale percentuale si dichiara fumatore? \n")

print(f"Tra le femmine, quale percentuale si dichiara non fumatore? \n")
print(f"Tra le femmine, quale percentuale si dichiara fumatore? \n")

print(f"Tra gli utenti non fumatori, quale percentuale è maschio? \n")
print(f"Tra gli utenti non fumatori, quale percentuale è femmina? \n")

print(f"Tra gli utenti fumatori, quale percentuale è maschio? \n")
print(f"Tra gli utenti fumatori, quale percentuale è femmina? \n")

Tra i maschi, quale percentuale si dichiara non fumatore? 

Tra i maschi, quale percentuale si dichiara fumatore? 

Tra le femmine, quale percentuale si dichiara non fumatore? 

Tra le femmine, quale percentuale si dichiara fumatore? 

Tra gli utenti non fumatori, quale percentuale è maschio? 

Tra gli utenti non fumatori, quale percentuale è femmina? 

Tra gli utenti fumatori, quale percentuale è maschio? 

Tra gli utenti fumatori, quale percentuale è femmina? 



In [14]:
# Solution




print("Sull'intera popolazione i maschi non fumatori sono il 47%")
print("Sull'intera popolazione i maschi fumatori sono il 12%")

print("Sull'intera popolazione le femmine non fumatrici sono il 34%")
print("Sull'intera popolazione le femmine fumatrici sono il 6%")

print("Tra i non fumatori i maschi sono l'58%")
print("Tra i non fumatori le femmine sono l'42%")

print("Tra i fumatori i maschi sono l'64%")
print("Tra i fumatori le femmine sono l'36%")




Sull'intera popolazione i maschi non fumatori sono il 47%
Sull'intera popolazione i maschi fumatori sono il 12%
Sull'intera popolazione le femmine non fumatrici sono il 34%
Sull'intera popolazione le femmine fumatrici sono il 6%
Tra i non fumatori i maschi sono l'58%
Tra i non fumatori le femmine sono l'42%
Tra i fumatori i maschi sono l'64%
Tra i fumatori le femmine sono l'36%


### 1.9 (opzionale)
Ripetere i punti precedenti considerando un'altra coppia di variabili categoriche. Potete raggruppare le variabili come sopra in modo da raggruppare una variabile categorica in pochi gruppi (es., per il campo "diet" potete formare tre gruppi: "Onnivori", "Vegetariani e Vegani", "Altro") oppure potete dividere una variabile numerica (es. età) in diversi gruppi (es. "giovani" con età < 25 anni, "meno giovani" con età tra 25 e 40 anni, "senior" con età superiore a 40 anni).

In [15]:
# Solution
arrayEta =df['age'].values
print(arrayEta)
dfEta = df.dropna(subset=['age'])

[22 35 38 ... 42 27 39]


In [16]:
anni = dfEta["age"].values
arrayanni = np.full(fuma.shape, "", dtype="object")
for i in range(len(arrayanni)):
    if anni[i] < 25:
        arrayanni[i] = "giovane"
    elif anni[i] >25 and anni[i]<40:
        arrayanni[i] = "meno giovane"
    else:
        arrayanni[i]="senior"
print(arrayanni)

#sexx = dfNew["sex"].values


categoria=["giovane","meno giovane","senior"]
tabEta = np.full((len(sex),len(categoria)), np.nan, dtype=int)
for u in range(len(sex)):
    for n in range(len(categoria)):
        tabEta[u,n] = np.sum((sexx==sex[u]) & (arrayanni==categoria[n]))
       # print(f"{sex[r]:8} {categoria[s]:12}: {tabEta[r,s]}")
#print(tabEta)
stampaEta=pd.DataFrame(tabEta, # dati
             index=sex, # intestazioni di riga
             columns=categoria) # intestazioni di colonna
print(stampaEta)

['giovane' 'meno giovane' 'meno giovane' ... 'meno giovane' 'giovane'
 'meno giovane']
   giovane  meno giovane  senior
m     5908         18488    7973
f     4004         12538    5523


In [17]:
trace1 = go.Bar(
    x=sex,
    y=tabEta[:,0],
    name=categoria[0]
)
trace2 = go.Bar(
    x=sex,
    y=tabEta[:,1],
    name=categoria[1]
)
trace3 = go.Bar(
    x=sex,
    y=tabEta[:,2],
    name=categoria[2]
)

data = [trace1, trace2,trace3]
layout = go.Layout(
    barmode='group',
    xaxis=dict(title="sesso"),
    yaxis=dict(title="divisione età")
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='grouped-bar')


In [18]:
# Solution

rigaEta= np.sum(tabEta, axis=1) 
colEta  = np.sum(tabEta, axis=0)

print(f"Frequenze assolute marginali per riga: {rigaEta}")#numero di donne vs numero di uomini
print(f"Frequenze assolute marginali per colonna: {colEta}")#numero fumatori vs numero non fumatori

Frequenze assolute marginali per riga: [32369 22065]
Frequenze assolute marginali per colonna: [ 9912 31026 13496]


In [19]:
# Solution

t_rel_eta=np.full(tabEta.shape, np.nan)
for k in range(tabEta.shape[0]): # per ogni riga (indice r)
    for z in range(tabEta.shape[1]): # per ogni colonna (indice s)
        t_rel_eta[k,z] = tabEta[k,z] / len(sexx)
t_rel_eta

array([[0.10853511, 0.33964067, 0.14647096],
       [0.07355697, 0.23033398, 0.10146232]])

In [20]:
# Solution

t_cond_rows_eta = np.full(tabEta.shape, np.nan)

for r in range(tabEta.shape[0]): # per ogni riga (indice r)
    for s in range(tabEta.shape[1]): # per ogni colonna (indice s)
        t_cond_rows_eta[r,s] = tabEta[r,s] / rigaEta[r]
t_cond_rows_eta

array([[0.18252031, 0.57116377, 0.24631592],
       [0.18146386, 0.56823023, 0.25030591]])

In [21]:
# Solution

t_cond_col_eta = np.full(tabEta.shape, np.nan)
for p in range(tabEta.shape[0]): # per ogni riga (indice r)
    for s in range(tabEta.shape[1]): # per ogni colonna (indice s)
        t_cond_col_eta[p,s] = tabEta[p,s] / colEta[s]
t_cond_col_eta

array([[0.5960452 , 0.59588732, 0.59076763],
       [0.4039548 , 0.40411268, 0.40923237]])

## Esercizio 2

Si consideri il dataset ``profili.csv`` considerato nell'esercizio precedente, escludendo gli studenti. Si consideri la variabile numerica ``età`` e la variabile categorica ``Lavoratore`` che assume valori "YES" (se l'utente dichiara di avere un lavoro), "NO" (se l'utente dichiara di non avere un lavoro). La cella sotto esclude dal dataset tutti gli utenti che sono studenti o che non dichiarano il proprio lavoro e raggruppa gli utenti in base alla variabile ``Lavoratore`` definita sopra. L'array finale è ``jobArray``. Opzionale: Provate a capire i comandi eseguiti nella cella sotto.  

In [22]:
dfNew = df.dropna(subset = ['job'])

m = len(dfNew['job'].values)
jobArray = np.full(m, "", dtype = object)

for i in range(m):
    if dfNew['job'].values[i] == 'unemployed':
        jobArray[i] = 'NO' 
    else:
        jobArray[i] = 'YES' 

### 2.1 
Disegnare un grouped boxplot che confronti la distribuzione dell'età per le varie sottoclassi identificate dalla variabile ``Lavoratore``.  

In [23]:
# Solution
# Rappresentazione come boxplot
support=np.unique(jobArray)
eta=dfNew['age'].values
data = []
for val in support:
    num_g = eta[jobArray == val] # tempi per le osservazioni corrispondenti
    trace = go.Box(x=num_g, name=val)
    data.append(trace)

layout = go.Layout(
    xaxis=dict(title="Età"),
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

### 2.2 
Simile al punto 2.1. Disegnare due istogrammi sovrapposti per confrontare la distribuzione dell'età per le varie sottoclassi identificate dalla variabile ``Lavoratore``. Perchè uno degli istogrammi non è ben visibile?

In [24]:
# Solution



# Solution
data = []
for val in support:
    num_g = eta[jobArray == val] # tempi per le osservazioni corrispondenti
    trace = go.Histogram(x=num_g, name=val)
    data.append(trace)

layout = go.Layout(
    barmode='group',
    xaxis=dict(title="Età"),
    yaxis=dict(title="Numero persone"),
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig)
#perchè il numero di persone che non hanno un lavoro per una determinata età sono molto meno rispetto a quelle che hanno lavoro e quindi l'istogramma del NO risulta poco visibile


### 2.3 (opzionale)

L'istogramma generato al punto precedente che rappresenta la distribuzione delle età degli utenti disoccupati non è ben visibile nella stessa figura dell'istogramma che rappresenta la distribuzione delle età degli utenti lavoratori poichè il numero di utenti disoccupati è molto piu' basso rispetto ai lavoratori. Di conseguenza, anche le barre dell'istogramma sono molto piu' basse rispetto alle barre dell'istogramma caratterizzante gli utenti lavoratori. In questo caso, sarebbe meglio "normalizzare" gli istogrammi, dove l'altezza delle barre non è la frequenza assoluta (numero di utenti in un intervallo di età), ma la frequenta relativa (frazione di utenti in un intervallo di età). La cella sotto mostra come generare un istogramma normalizzato (basta impostare l'attributo ``histnorm`` uguale a ``probability'`` quando si creare l'oggetto della classe ``go.Histogram``).  

In [25]:
#Hint


Generate adesso gli istogrammi normalizzati dell'età dei disoccupati e dei lavoratori.

In [34]:
# Solution


# Solution
data = []
for val in support:
    print(val)
    num_g = eta[jobArray == val] # tempi per le osservazioni corrispondenti
    trace = go.Histogram(x=num_g, name=val,histnorm = 'probability')
    data.append(trace)

layout = go.Layout(
    barmode='group',
    xaxis=dict(title="Età"),
    yaxis=dict(title="Numero persone"),
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

NO
YES


### 2.4 (opzionale)
Ripetere l'analisi bivariata dell'esercizio utilizzando un'altra variabile categorica e/o un'altra variabile numerica. Ad esempio, potete studiare la relazione tra età degli utenti e reddito (dividendo il reddito in 3 gruppi). Hint: se guardate i redditi dichiarati compare spesso '-1', che equivale al campo non compilato dall'utente (vedi cella sotto). Se volete fare un'analisi dei redditi, rimuovete questi utenti nella vostra analisi come mostrato nella cella sotto.

In [27]:
# Hint
print(df['income'].values)

maskIndex = df['income'].values != -1 
arrayIncome = df['income'].values[maskIndex]
arrayAgeNew = df['age'].values[maskIndex] 

[    -1  80000     -1 ... 100000     -1     -1]


## Esercizio 3
Si consideri il dataset [Numbeo](https://www.numbeo.com/cost-of-living/), che fornisce informazioni e indici per misurare le condizioni di vita nei vari Paesi del mondo (misurate in termini di costo della vita, tasso di criminalità, inquinamento, traffico, etc.).

Eseguiamo la cella sotto e importiamo con pandas la [tabella](https://www.numbeo.com/quality-of-life/rankings_by_country.jsp) che riporta i principali indicatori per misurare la qualità della vita in un Paese, e concentriamoci sui due attributi **costo della vita** (``Cost of Living Index`` nella tabella) e **tasso di inquinamento** (``Pollution Index`` nella tabella).

In [28]:
# Da eseguire per importare i dati

# Create pandas dataframe
dfLife = pd.read_html('https://www.numbeo.com/quality-of-life/rankings_by_country.jsp')
dfLife = dfLife[2] 

# Select attributes Country, Cost of Living Index, and Pollution Index

arrayCountry = dfLife['Country'].values            # Nomi dei Paesi
arrayCost = dfLife['Cost of Living Index'].values
arrayPollution = dfLife['Pollution Index'].values

### 3.1
Disegnare lo scatterplot tra le variabili **costo della vita** e **tasso di inquinamento**. Guardando il grafico appena generato, le due variabili sono tra loro correlate? Sempre guardando il grafico, sapete già dire se il coefficiente di correlazione sarà positivo, negativo, o circa nullo?  

In [29]:
# Hint per generare uno scatter plot

xData = np.random.rand(1000)
yData = 2*xData + 0.3*np.random.randn(1000)

trace = go.Scatter(x = xData, y = yData,  
                   mode = 'markers', 
                   marker = {'color': 'rgb(255,0,0)', 'size': 5, 'symbol': 'circle', 'opacity': 0.5}) 

layout = go.Layout( title = 'Scatterplot (x vs y)',
                    xaxis = {'title': 'x'},
                    yaxis = {'title': 'y'})
fig = go.Figure(data = [trace], layout = layout)
py.iplot(fig)

In [30]:
# Solution
#le due variabili non sono fortemente correlate e avranno un indice di correlazione circa pari a 0 in quanto segue 
#non sembra suguire una retta
data = [go.Scatter(x=arrayCost, y=arrayPollution, mode='markers')]
layout = go.Layout(
    xaxis=dict(title="Costo della vita"),
    yaxis=dict(title="Tasso di inquinamento"),
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)



### 3.2 
Calcolare il coefficiente di correlazione tra le variabili *costo della vita* e *tasso di inquinamento*.

In [31]:
# Hint
# Per calcolare la matrice di correlazione tra le varianili 'a' e 'b'

a = np.array([2,4,5,8])
b = - np.array([2,6,1,9])

coeff = np.corrcoef([a,b])
print(coeff)

[[ 1.         -0.70330232]
 [-0.70330232  1.        ]]


In [32]:
# Solution
print(np.corrcoef(arrayCost,arrayPollution))

[[ 1.        -0.6682972]
 [-0.6682972  1.       ]]


### 3.3 (opzionale, per ripassare l'analisi univariata)
Disegnare l'istogramma e il boxplot della variabile **indice sulla qualità delle vita** (colonna ``Quality of Life Index`` del dataframe importato prima). Calcolare media, mediana, varianza, e deviazione standard, primo e terzo quartile, 90-esimo percentile. E' giusto dire (secondo i dati di Numbeo) che la Svizzera è tra il 10% dei paesi con l'indice di qualità della vita piu' alto?

In [33]:
# Solution

# Solution
arrayQuality = dfLife['Quality of Life Index'].values
data = [go.Histogram(x=arrayQuality)] # Variante: prova a usare "y=a" come parametro
py.iplot(data)
#boxplot
dat1 = [go.Box(x=arrayQuality)] 
py.iplot(dat1)
print(f"la media e\' :{np.mean(arrayQuality)}")
print(f"la mediana e\' :{np.median(arrayQuality)}")
#varianza
print(f"la varianza dei tiri e\':{np.var(arrayQuality)}")
#devizaione standard
print(f"la deviazione standard dei tiri e\' : {np.std(arrayQuality)}")
#primo quartile
print(f"il primo quartile e\' :{np.percentile(arrayQuality,25)}")
#terzo quartile
print(f"il terzo quartile e\' :{np.percentile(arrayQuality,75)}")
print(f"il 90-esimo percentile e\' :{np.percentile(arrayQuality,90)}")


la media e' :146.0787878787879
la mediana e' :152.59
la varianza dei tiri e':1046.818683379247
la deviazione standard dei tiri e' : 32.35457747180833
il primo quartile e' :121.3925
il terzo quartile e' :174.39999999999998
il 90-esimo percentile e' :187.10500000000002
